{
 "title": "web-api-service",
 "tags": [ "web-api-service" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(sum by (pod) (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"\",pod=~\"web-api-service-.*\"}[2m])))",
     "legendFormat": "usage"
    },
    {
     "expr": "max(kubernetes_io:container_cpu_request_cores{pod_name=~\"web-api-service-.*\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kubernetes_io:container_cpu_limit_cores{pod_name=~\"web-api-service-.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubernetes_io:container_cpu_limit_utilization{pod_name=~\"web-api-service-.*\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(sum by (pod) (container_memory_rss{image!=\"\",container!=\"\",pod=~\"web-api-service-.*\"}))",
     "legendFormat": "usage"
    },
    {
     "expr": "max(kubernetes_io:container_memory_request_bytes{pod_name=~\"web-api-service-.*\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kubernetes_io:container_memory_limit_bytes{pod_name=~\"web-api-service-.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubernetes_io:container_memory_limit_utilization{pod_name=~\"web-api-service-.*\"})",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}